### ISSUE TITLE
consolidate duplicate news items

### ISSUE THREAD

**Issue by bbest** [cstories-app/beta#3]
Like here:

![image](https://user-images.githubusercontent.com/2837257/213298050-87df2693-5a21-40c7-a507-615472c6480d.png)

## 2 (robust): pick first, add other sources to page

```yaml
title:
content:
other sources: [source_name](source_url), [source_name](source_url)
```

Group by title, collapse rest into data and proceed:

```r
d_sources <- d_news |>
  group_by(title) |>
  nest()
```
